(define (problem mapf-problem2)
    (:domain mapf)
    (:requirements :strips)
    (:objects
        v1 v2 v3 v4 v5 v6 v7 - vertex
        a1 a7 - agent)
    (:init
        (at a1 v4)
        (at a7 v6)
        (adjacent v1 v2)
        (adjacent v2 v1)
        (adjacent v1 v3)
        (adjacent v3 v1)
        (adjacent v2 v5)
        (adjacent v5 v2)
        (adjacent v3 v4)
        (adjacent v4 v3)
        (adjacent v4 v5)
        (adjacent v5 v4)
        (adjacent v5 v6)
        (adjacent v6 v5)
        (adjacent v7 v5)
        (adjacent v5 v7)
        (occupied v4)
        (occupied v6)
        )
    (:goal (and
     (at a1 v1)
     (at a7 v7)
     )
    )
)